# https://hub.docker.com/r/library/python/tags/
image: python:3.12.3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install tox
    - tox -e py # run unit tests
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

check:
  script:
    - pip install tox ruff  # you can also use tox
    - tox -e lint,type,style # run linter, type checker and style checks

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Probably has no added value unless we do integration testing here
# run:
#   script:
#     - pip install -r requirements.txt
#     - python -m xrpl_controller
#   artifacts:
#     paths:
#       - build/*