"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    FROM_HOSTNAME_FIELD_NUMBER: builtins.int
    TO_HOSTNAME_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    from_hostname: builtins.str
    to_hostname: builtins.str
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        from_hostname: builtins.str = ...,
        to_hostname: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "from_hostname", b"from_hostname", "to_hostname", b"to_hostname"]) -> None: ...

global___Packet = Packet

@typing.final
class PacketAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    SEND_AMOUNT_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    action: builtins.int
    send_amount: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        action: builtins.int = ...,
        send_amount: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "data", b"data", "send_amount", b"send_amount"]) -> None: ...

global___PacketAck = PacketAck

@typing.final
class ValidatorNodeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOSTNAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALIDATION_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_SEED_FIELD_NUMBER: builtins.int
    hostname: builtins.str
    status: builtins.str
    validation_key: builtins.str
    validation_private_key: builtins.str
    validation_public_key: builtins.str
    validation_seed: builtins.str
    def __init__(
        self,
        *,
        hostname: builtins.str = ...,
        status: builtins.str = ...,
        validation_key: builtins.str = ...,
        validation_private_key: builtins.str = ...,
        validation_public_key: builtins.str = ...,
        validation_seed: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hostname", b"hostname", "status", b"status", "validation_key", b"validation_key", "validation_private_key", b"validation_private_key", "validation_public_key", b"validation_public_key", "validation_seed", b"validation_seed"]) -> None: ...

global___ValidatorNodeInfo = ValidatorNodeInfo

@typing.final
class ValidatorNodeInfoAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___ValidatorNodeInfoAck = ValidatorNodeInfoAck

@typing.final
class GetConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetConfig = GetConfig

@typing.final
class Partition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes"]) -> None: ...

global___Partition = Partition

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOSTNAME_PREFIX_FIELD_NUMBER: builtins.int
    NUMBER_OF_NODES_FIELD_NUMBER: builtins.int
    NET_PARTITIONS_FIELD_NUMBER: builtins.int
    UNL_PARTITIONS_FIELD_NUMBER: builtins.int
    hostname_prefix: builtins.str
    number_of_nodes: builtins.int
    @property
    def net_partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Partition]: ...
    @property
    def unl_partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Partition]: ...
    def __init__(
        self,
        *,
        hostname_prefix: builtins.str = ...,
        number_of_nodes: builtins.int = ...,
        net_partitions: collections.abc.Iterable[global___Partition] | None = ...,
        unl_partitions: collections.abc.Iterable[global___Partition] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hostname_prefix", b"hostname_prefix", "net_partitions", b"net_partitions", "number_of_nodes", b"number_of_nodes", "unl_partitions", b"unl_partitions"]) -> None: ...

global___Config = Config
