min_priority: 1
max_priority: 100
# dispatch_interval_ms: 20
target_inbox: 10
overflow_factor: 1.2
underflow_factor: 0.8
sensitivity_ratio: 1.2
max_events: 100

# Message type priorities configuration
# Lower number priority is sent first
priority_list:
  2: 50 # ripple_pb2.TMManifests,
  3: 50 # ripple_pb2.TMPing,
  5: 50 # ripple_pb2.TMCluster,
  15: 50 # ripple_pb2.TMEndpoints,
  30: 50 # ripple_pb2.TMTransaction,
  31: 50 # ripple_pb2.TMGetLedger,
  32: 50 # ripple_pb2.TMLedgerData,
  33: 50 # ripple_pb2.TMProposeSet,
  34: 50 # ripple_pb2.TMStatusChange,
  35: 50 # ripple_pb2.TMHaveTransactionSet,
  41: 50 # ripple_pb2.TMValidation,
  42: 50 # ripple_pb2.TMGetObjectByHash,
  # 50: Is not defined in proto file and has no corresponding class, but appears in enum.
  # 51: Is not defined in proto file and has no corresponding class, but appears in enum.
  52: 50 # ripple_pb2.TMGetPeerShardInfo,
  53: 50 # ripple_pb2.TMPeerShardInfo,
  54: 50 # ripple_pb2.TMValidatorList,
  55: 50 # ripple_pb2.TMSquelch,
  56: 50 # ripple_pb2.TMValidatorListCollection,
  57: 50 # ripple_pb2.TMProofPathRequest,
  58: 50 # ripple_pb2.TMProofPathResponse,
  59: 50 # ripple_pb2.TMReplayDeltaRequest,
  60: 50 # ripple_pb2.TMReplayDeltaResponse,
  61: 50 # ripple_pb2.TMGetPeerShardInfoV2,
  62: 50 # ripple_pb2.TMPeerShardInfoV2,
  63: 50 # ripple_pb2.TMHaveTransactions,
  64: 50 # ripple_pb2.TMTransactions