min_priority: 1
max_priority: 100
# dispatch_interval_ms: 20
target_inbox: 10
overflow_factor: 1.2
underflow_factor: 0.8
sensitivity_ratio: 1.2
max_events: 100

# Message type priorities configuration
# Lower number priority is sent first
priority_list:
  TMManifests: 90
  TMEndpoints: 85
  TMProposeSet: 80
  TMValidation: 75
  TMStatusChange: 70
  TMHaveTransactionSet: 65
  TMTransaction: 60
  TMGetLedger: 55
  TMGetObjectByHash: 50
  TMTransactionSet: 45
  TMConsensus: 40
  TMPeerShardInfo: 35
  TMHaveSet: 30
  TMLedgerData: 25
  TMGetPeerShardInfo: 20
  TMValidatorList: 15
  TMValidatorListCollection: 10
  # Add any other message types with their priorities