fields:
  - name: drop_probability
    value: 0.01
  - name: delay_probability
    value: 0.04
  - name: min_delay_ms
    value: 1
  - name: max_delay_ms
    value: 150
  - name: seed
    value: null
